version: '3.1'
services:
  stats-server:
    build: ./statistics/server
    image: stats-server:0.0.1SNAPSHOT
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats


  stats-db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: stats-db-postgres
    ports:
      - "7654:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  ewm-service:
    build: ./main-service
    image: main-service:0.0.1SNAPSHOT
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - STATS_SERVER_URL=http://stats-server:9090
  ewm-db:
          image: postgres:15-alpine
          container_name: ewm-db-postgres

          ports:
            - "6543:5432"
          environment:
            - POSTGRES_DB=ewm-main
            - POSTGRES_USER=ewm-main
            - POSTGRES_PASSWORD=ewm-main
