version: '3.1'
services:
  stats-server:
    build: ./statistics/server
    image: stats-server:0.0.1SNAPSHOT
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats


  stats-db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: stats-db-postgres
    ports:
      - "7654:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  ewm-service:
    build: ./main-service
    image: main-service:0.0.1SNAPSHOT
    container_name: main-service
    ports:
      - "8080:8080"

  ewm-db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ewn-db
    ports:
            - "6543:5432"

