version: '3.1'
services:
  stats-server:
    build: ./statistics/server
    container_name: stServer
    image: st-s
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - DB_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root




  stats-client:
    build: ./statistics/client
    container_name: stClient
    image: st-client
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - CLIENT_PORT=8080
      - STATS_SERVER_URL=http://stats-server:9090


  ewn-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine